---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/applications":
    get:
      summary: Show application
      tags: 
        - Application
      responses:
        '200':
          description: Successful
    post:
      summary: Creat new application
      tags: 
        - Application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Test Application 
      responses:
        '201':
          description: Application created successfully
        '422':
          description: Validation errors occurred
  "/api/v1/applications/{token}":
    patch:
      summary: "Update application"
      tags: 
        - Application
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: "Token of the application"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Application name"    
      responses: 
        '200':
          description: Application updated successfully
        '422':
          description: Validation errors occurred

  "/api/v1/applications/{token}/chats":
    get:
      summary: "List chats for a specific application"
      tags: 
        - Chat
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: "Token of the application"
      responses:
        '200':
          description: "List of chats"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: integer
                      description: "Chat number"
                    messages_count:
                      type: integer
                      description: "Number of messages in the chat"
        '404':
          description: "Application not found"
    post:
      summary: "Create new Chat"
      tags: 
        - Chat
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: "Token of the application"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              description: "Optional request body (if needed)" 
      responses:
        '201':
          description: "Chat created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  number:
                    type: integer
                    description: "Chat number"
        '404':
          description: "Application not found"
  "/api/v1/applications/{token}/chats/{number}/messages":
    post:
      summary: "Create new message"
      tags:
        - Message
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: "Token of the application"
        - in: path
          name: number
          required: true
          schema:
            type: integer
          description: "Chat number"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                  example: "This is a sample message body"
      responses:
        '201':
          description: "Message created successfully"
        '404':
          description: "Chat or application not found"
  "/api/v1/applications/{token}/chats/{number}/messages/search":
    get:
      summary: "Search messages for a specific chat"
      tags: 
        - Message
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: "Token of the application"
        - in: path
          name: number
          required: true
          schema:
            type: integer
          description: "Chat number"
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: "Search query for message bodies"
      responses:
        '200':
          description: "Search results"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: integer
                      description: "Message number"
                    body:
                      type: string
                      description: "Message body"
        '404':
          description: "Application or chat not found"
        '422':
          description: "Validation error"

servers:
  - url: http://localhost:3000
    description: "Chat System API V1"
